apiVersion: v1
kind: Service
metadata:
  name: factorio
spec:
  ports:
  - name: "27015"
    port: 27015
    targetPort: 27015
  selector:
    app: factorio
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: factorio
  name: factorio
spec:
  selector:
    matchLabels:
      app: factorio
  replicas: 1
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
      - env:
        - name: factorio_DATABASE
          value: espresso
        - name: factorio_ROOT_PASSWORD
          value: root
        image: factoriotools/factorio
        name: factorio
        ports:
        - containerPort: 27015
        resources:
          requests:
            memory: "2Gi"
        volumeMounts:
        - mountPath: /opt/factorio
          name: factorio
        resources:
          limits:
            memory: "2Gi"
          requests:
            memory: "512M"
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: factorio
    spec:
      resources:
        requests:
          storage: 2Gi
      accessModes:
      - ReadWriteOnce