apiVersion: v1
kind: Service
metadata:
  name: factorio
spec:
  ports:
  - name: "34197"
    port: 34197
    targetPort: 34197
    protocol: UDP
  selector:
    app: factorio
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: factorio
  name: factorio
spec:
  selector:
    matchLabels:
      app: factorio
  replicas: 1
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
      - env:
        - name: PORT
          value: 34197
        image: factoriotools/factorio
        imagePullPolicy: Always
        name: factorio
        ports:
        - containerPort: 34197
          protocol: UDP
        - containerPort: 27015
          protocol: TCP
        resources:
          requests:
            memory: "2Gi"
        volumeMounts:
        - mountPath: /factorio
          name: factorio
        resources:
          limits:
            memory: "2Gi"
          requests:
            memory: "512M"
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: factorio
    spec:
      resources:
        requests:
          storage: 2Gi
      accessModes:
      - ReadWriteOnce